### ISSUE TITLE
Using the hook causes Ionic to be unable to find modules.

### ISSUE THREAD

**Issue by Kurtz1993** [alastairparagas/cordova-minify#11]
I've compiled my application using the minify hook, but when I try to run it I get a message in the debugger that says it cannot be able to find the module:
![capture](https://cloud.githubusercontent.com/assets/5412470/7567607/aa3a7446-f7c3-11e4-9744-2e52efef8259.PNG)

Tried adding the .min.js file of ionic bundle, similar result:
![capture1](https://cloud.githubusercontent.com/assets/5412470/7567651/e7d0eda8-f7c3-11e4-8746-aa46a991de40.PNG)

Will Ionic support be added?

**Comment by alastairparagas** [comment]
@Kurtz1993 I primarily designed this cordova build tool because I was working on an Ionic project (so Ionic support has been there since the beginning). 

The problem with your error is that you are not using [Angular's minification-safe syntax](http://thegreenpizza.github.io/2013/05/25/building-minification-safe-angular.js-applications/).

**Comment by Kurtz1993** [comment]
Thanks for the tip!
